export const funds_info = [
  { name: "VNINDEX", type: "Index" },
  { name: "VN30", type: "Index" },
  { name: "DCDS", type: "Active", company: "Dragon Capital" },
  { name: "DCDE", type: "Active", company: "Dragon Capital" },
  { name: "DCBF", type: "Bond", company: "Dragon Capital" },
  { name: "DCIP", type: "Bond", company: "Dragon Capital" },
  { name: "E1VFVN30", type: "ETF", company: "Dragon Capital" },
  { name: "FUEVFVND", type: "ETF", company: "Dragon Capital" },
  { name: "FUEDCMID", type: "ETF", company: "Dragon Capital" },
  { name: "TCEF", type: "Active", company: "Techcom Capital" },
  { name: "TCBF", type: "Bond", company: "Techcom Capital" },
  { name: "TCFF", type: "Bond", company: "Techcom Capital" },
  { name: "TCFIN", type: "Active", company: "Techcom Capital" },
  { name: "VCBFMGF", type: "Active", company: "VCBF" },
  { name: "VCBFTBF", type: "Active", company: "VCBF" },
  { name: "VCBFBCF", type: "Active", company: "VCBF" },
  { name: "VCBFFIF", type: "Bond", company: "VCBF" },
  { name: "VESAF", type: "Active", company: "VinaCapital" },
  { name: "VEOF", type: "Active", company: "VinaCapital" },
  { name: "VIBF", type: "Active", company: "VinaCapital" },
  { name: "VFF", type: "Bond", company: "VinaCapital" },
  { name: "VLBF", type: "Bond", company: "VinaCapital" },
  { name: "FUEVN100", type: "ETF", company: "VinaCapital" },
  { name: "SSISCA", type: "Active", company: "SSIAM" },
  { name: "SSIBF", type: "Bond", company: "SSIAM" },
  { name: "VLGF", type: "Active", company: "SSIAM" },
  { name: "FUESSV50", type: "ETF", company: "SSIAM" },
  { name: "FUESSVFL", type: "ETF", company: "SSIAM" },
  { name: "FUESSV30", type: "ETF", company: "SSIAM" },
  { name: "BVFED", type: "Active", company: "Baoviet Fund" },
  { name: "BVBF", type: "Bond", company: "Baoviet Fund" },
  { name: "BVPF", type: "Active", company: "Baoviet Fund" },
  { name: "ENF", type: "Active", company: "Eastspring" },
  { name: "VNDAF", type: "Active", company: "IPAAM" },
  { name: "VNDBF", type: "Bond", company: "IPAAM" },
  { name: "FUEIP100", type: "ETF", company: "IPAAM" },
  { name: "MAFEQI", type: "Active", company: "Manulife IM" },
  { name: "MAFBAL", type: "Active", company: "Manulife IM" },
  { name: "MBVF", type: "Active", company: "MB Capital" },
  { name: "MBBOND", type: "Bond", company: "MB Capital" },
  { name: "FUEMAV30", type: "ETF", company: "Mirae Asset" },
  { name: "FUEKIV30", type: "ETF", company: "KIM" },
  { name: "FUEKIVFS", type: "ETF", company: "KIM" },
];

export const zoom_periods = ["1M", "3M", "6M", "YTD", "1Y", "3Y", "All"];

export const fund_types = ["Index", "ETF", "Active", "Bond"];

export const defaultFunds = ["VNINDEX", "DCDS", "E1VFVN30", "TCEF", "VESAF"];
