import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  funds: defineTable({
    user: v.id("users"),
    Date: v.string(),
    DCDS: v.string(),
    DCDE: v.string(),
    DCBF: v.string(),
    DCIP: v.string(),
    E1VFVN30: v.string(),
    FUEVFVND: v.string(),
    FUEDCMID: v.string(),
    TCEF: v.string(),
    TCBF: v.string(),
    TCFF: v.string(),
    TCFIN: v.string(),
    VCBFMGF: v.string(),
    VCBFTBF: v.string(),
    VCBFBCF: v.string(),
    VCBFFIF: v.string(),
    VESAF: v.string(),
    VEOF: v.string(),
    VIBF: v.string(),
    VFF: v.string(),
    VLBF: v.string(),
    FUEVN100: v.string(),
    SSISCA: v.string(),
    SSIBF: v.string(),
    VLGF: v.string(),
    FUESSV50: v.string(),
    FUESSVFL: v.string(),
    FUESSV30: v.string(),
    BVFED: v.string(),
    BVBF: v.string(),
    BVPF: v.string(),
    ENF: v.string(),
    VNDAF: v.string(),
    VNDBF: v.string(),
    FUEIP100: v.string(),
    MAFEQI: v.string(),
    MAFBAL: v.string(),
    MBVF: v.string(),
    MBBOND: v.string(),
    FUEMAV30: v.string(),
    FUEKIV30: v.string(),
    FUEKIVFS: v.string(),
    VNINDEX: v.string(),
    VN30: v.string(),
  }),
  users: defineTable({
    email: v.string(),
    imageUrl: v.string(),
    clerkId: v.string(),
    name: v.string(),
  }),
});
